name: namma-ai agent-m
services:
 frontend:
   build: ./frontend
   container_name: agentic-frontend
   ports:
     - "13001:3000"
   depends_on:
     - api-gateway
   networks:
     - agentic-network
 auth-service:
   build: ./auth-service
   container_name: agentic-auth-service
   ports:
     - "13002:8001"
   networks:
     - agentic-network
 api-gateway:
   build: ./api-gateway
   container_name: agentic-api-gateway
   ports:
     - "13003:3001"
   depends_on:
     - workflow-orchestrator
   networks:
     - agentic-network
 workflow-orchestrator:
   build: ./workflow-orchestrator
   container_name: agentic-workflow
   ports:
     - "13004:5000"
   depends_on:
     - temporal
   networks:
     - agentic-network
 logging:
   build: ./logging
   container_name: agentic-logging
   ports:
     - "13006:5601"
     - "13007:9200"
   networks:
     - agentic-network
 websocket-service:
   build: ./websocket-service
   container_name: agentic-websocket
   ports:
     - "13008:5000"
   networks:
     - agentic-network
 ai-processor:
   build: ./ai-processor
   container_name: agentic-ai-processor
   ports:
     - "13009:5000"
   networks:
     - agentic-network
 ai-action-service:
   build: ./ai-action-service
   container_name: agentic-ai-action-service
   ports:
     - "13010:5000"
   networks:
     - agentic-network  
 ai-prompt-service:
   build: ./ai-prompt-service
   container_name: agentic-ai-prompt-service
   ports:
     - "13011:5000"
   networks:
     - agentic-network  
 data-preprocessing:
   build: ./data-preprocessing
   container_name: agentic-data-preprocessor
   ports:
     - "13012:5000"
   networks:
     - agentic-network
 event-bus:
   build: ./event-bus
   container_name: agentic-event-bus
   ports:
     - "13013:5000"
   networks:
     - agentic-network
 storage:
   image: minio/minio
   container_name: agentic-storage
   ports:
     - "9000:9000"
     - "9001:9001"
   command: server /data --console-address ":9001"
   networks:
     - agentic-network
 task-queue:
   build: ./task-queue
   container_name: agentic-task-queue
   depends_on:
     - redis
   networks:
     - agentic-network
 kafka:
   image: bitnami/kafka:latest
   container_name: agentic-kafka
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_LISTENERS: PLAINTEXT://:9092
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   depends_on:
     - zookeeper
   networks:
     - agentic-network
   ports:
     - "9092:9092"
 zookeeper:
   image: bitnami/zookeeper:latest
   container_name: agentic-zookeeper
   environment:
     ALLOW_ANONYMOUS_LOGIN: "yes"
   networks:
     - agentic-network
   ports:
     - "2181:2181"
 redis:
   image: redis:alpine
   container_name: agentic-redis
   ports:
     - "6379:6379"
   networks:
     - agentic-network
 database:
   image: postgres:15
   container_name: agentic-db
   environment:
     POSTGRES_DB: agentic_db
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
   ports:
     - "5432:5432"
   networks:
     - agentic-network
 vector-db:
   image: ankane/pgvector
   container_name: agentic-vector-db
   environment:
     POSTGRES_DB: vector_db
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
   ports:
     - "5433:5432"
   networks:
     - agentic-network
 temporal:
   image: temporalio/auto-setup:latest
   container_name: temporal-server
   ports:
     - "7233:7233"
   networks:
     - agentic-network
networks:
 agentic-network:
   driver: bridge
