services:
 frontend:
   build: ./frontend
   container_name: agentic-frontend
   ports:
     - "3000:3000"
   depends_on:
     - api-gateway
   networks:
     - agentic-network
 api-gateway:
   build: ./api-gateway
   container_name: agentic-api-gateway
   ports:
     - "8000:8000"
   depends_on:
     - workflow-orchestrator
   networks:
     - agentic-network
 workflow-orchestrator:
   build: ./workflow-orchestrator
   container_name: agentic-workflow
   ports:
     - "5001:5000"
   depends_on:
     - temporal
   networks:
     - agentic-network
 logging:
   build: ./logging
   container_name: agentic-logging
   ports:
     - "5601:5601"
     - "9200:9200"
   networks:
     - agentic-network
 websocket-service:
   build: ./websocket-service
   container_name: agentic-websocket
   ports:
     - "5007:5000"
   networks:
     - agentic-network
 ai-processor:
   build: ./ai-processor
   container_name: agentic-ai-processor
   ports:
     - "5002:5000"
   networks:
     - agentic-network
 ai-action-service:
   build: ./ai-action-service
   container_name: agentic-ai-action-service
   ports:
     - "5022:5000"
   networks:
     - agentic-network  
 ai-prompt-service:
   build: ./ai-prompt-service
   container_name: agentic-ai-prompt-service
   ports:
     - "5032:5000"
   networks:
     - agentic-network  
 data-preprocessing:
   build: ./data-preprocessing
   container_name: agentic-data-preprocessor
   ports:
     - "5003:5000"
   networks:
     - agentic-network
 event-bus:
   build: ./event-bus
   container_name: agentic-event-bus
   ports:
     - "5006:5000"
   networks:
     - agentic-network
 storage:
   image: minio/minio
   container_name: agentic-storage
   ports:
     - "9000:9000"
     - "9001:9001"
   command: server /data --console-address ":9001"
   networks:
     - agentic-network
 task-queue:
   build: ./task-queue
   container_name: agentic-task-queue
   depends_on:
     - redis
   networks:
     - agentic-network
 redis:
   image: redis:alpine
   container_name: agentic-redis
   ports:
     - "6379:6379"
   networks:
     - agentic-network
 database:
   image: postgres:15
   container_name: agentic-db
   environment:
     POSTGRES_DB: agentic_db
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
   ports:
     - "5432:5432"
   networks:
     - agentic-network
 vector-db:
   image: ankane/pgvector
   container_name: agentic-vector-db
   environment:
     POSTGRES_DB: vector_db
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
   ports:
     - "5433:5432"
   networks:
     - agentic-network
 temporal:
   image: temporalio/auto-setup:latest
   container_name: temporal-server
   ports:
     - "7233:7233"
   networks:
     - agentic-network
networks:
 agentic-network:
   driver: bridge
